import type { Category, Product } from "@/types";

const U = (id: string) => `https://images.unsplash.com/photo-${id}?w=600&h=600&fit=crop&auto=format&q=80`;
const YT = (q: string) => `https://www.youtube.com/results?search_query=${encodeURIComponent(q)}`;

export const CAT_META: Record<Category, { icon: string; en: string; color: string; accent: string; dark: string }> = {
  スキンケア:   { icon: "🌸", en: "Skincare",   color: "#FDE8EC", accent: "#C4556A", dark: "#8B2E3F" },
  ヘアケア:     { icon: "💆", en: "Haircare",   color: "#E0EEF8", accent: "#4A8BAD", dark: "#2C5F78" },
  メイク:       { icon: "💄", en: "Makeup",     color: "#F5D5EA", accent: "#AD4A8B", dark: "#7A2C61" },
  ボディ:       { icon: "🫧", en: "Body",       color: "#D5F0E8", accent: "#4AAD8B", dark: "#2C7861" },
  UVケア:       { icon: "☀️", en: "UV Care",    color: "#FDF0D5", accent: "#C49A2A", dark: "#8A6C10" },
  フレグランス: { icon: "🌹", en: "Fragrance",  color: "#EAD5F5", accent: "#8B4AAD", dark: "#612C78" },
  ネイル:       { icon: "💅", en: "Nail",       color: "#F5D8D8", accent: "#AD4A4A", dark: "#782C2C" },
  サプリ:       { icon: "💊", en: "Supplement", color: "#D5F0D5", accent: "#4AAD4A", dark: "#2C782C" },
};

export const PRODUCTS: Product[] = [
  // スキンケア
  {
    id: 1, cat: "スキンケア", sub: "クリーム", name: "CICAクリーム", brand: "Dr.Jart+",
    price: 3960, rating: 4.8, rev: 23100, free: true,
    desc: "ツボクサエキスで炎症を鎮め、強力なバリアを形成。敏感肌の定番クリーム。",
    tags: ["敏感肌", "赤み鎮静", "保湿", "乾燥"],
    image: U("1556228578-8c89e6adf883"),
    note: "敏感肌でも安心して使えるバリア機能強化クリーム。",
    video: { title: "敏感肌が1週間試した【CICAクリーム比較】", views: "201万", url: YT("Dr.Jart CICAクリーム レビュー 敏感肌") },
  },
  {
    id: 2, cat: "スキンケア", sub: "美容液", name: "ナイアシンアミド10%+亜鉛1%", brand: "The Ordinary",
    price: 1540, rating: 4.4, rev: 18900, free: true,
    desc: "コスパ最強の毛穴・くすみ対策。ナイアシンアミド10%配合でテクスチャー軽め。",
    tags: ["毛穴", "くすみ", "皮脂コントロール", "混合肌"],
    image: U("1620756236308-65c3ef5d25f3"),
    note: "プチプラなのに皮膚科医も認める成分配合。",
    video: { title: "プチプラで毛穴消えた話｜1ヶ月検証", views: "156万", url: YT("The Ordinary ナイアシンアミド 毛穴 レビュー") },
  },
  {
    id: 3, cat: "スキンケア", sub: "化粧水", name: "極潤ヒアルロン液", brand: "肌ラボ",
    price: 880, rating: 4.6, rev: 45200, free: true,
    desc: "5種のヒアルロン酸配合。とろみのある高保湿化粧水。コスパ王者。",
    tags: ["乾燥", "保湿", "敏感肌", "プチプラ"],
    image: U("1556228720-195a672e8a03"),
    note: "ドラッグストアで買えるヒアルロン酸の最適解。",
    video: { title: "【肌ラボ】毎日使える保湿化粧水の正解", views: "89万", url: YT("肌ラボ 極潤 ヒアルロン酸 化粧水 使い方") },
  },
  {
    id: 4, cat: "スキンケア", sub: "美容液", name: "レチノールセラム 0.3%", brand: "Paula's Choice",
    price: 7700, rating: 4.7, rev: 8400, free: false,
    desc: "医薬品グレードのレチノール。エイジングケアの最終兵器。夜用・徐々に導入推奨。",
    tags: ["エイジングケア", "ハリ", "シワ", "毛穴"],
    image: U("1556228578-8c89e6adf883"),
    note: "米国皮膚科学会推奨成分を贅沢に使用したエイジングケアの切り札。",
    video: { title: "皮膚科医が解説｜レチノールの正しい使い方", views: "312万", url: YT("レチノール 使い方 エイジングケア 皮膚科") },
  },
  {
    id: 5, cat: "スキンケア", sub: "洗顔", name: "酵素洗顔パウダー", brand: "FANCL",
    price: 1980, rating: 4.5, rev: 31000, free: false,
    desc: "酵素がタンパク汚れを分解。毛穴の黒ずみ・角栓にしっかりアプローチ。",
    tags: ["毛穴", "角栓", "乾燥肌", "敏感肌"],
    image: U("1620756236308-65c3ef5d25f3"),
    note: "使い切りタイプで衛生的。週2〜3回のスペシャルケアに。",
    video: { title: "毛穴レス肌への近道【酵素洗顔比較】", views: "67万", url: YT("FANCL 酵素洗顔 毛穴 黒ずみ 効果") },
  },
  // ヘアケア
  {
    id: 6, cat: "ヘアケア", sub: "ヘアオイル", name: "エルジューダ MO", brand: "ミルボン",
    price: 2530, rating: 4.8, rev: 12400, free: true,
    desc: "モロッカンオイル配合。高熱から髪を守る熱保護機能あり。アイロン前に◎",
    tags: ["ヘアオイル", "熱保護あり", "しっとり", "剛毛・硬め"],
    image: U("1522338242992-e1a54906a8da"),
    note: "サロン専売の中でも特に人気の高いロングセラー。",
    video: { title: "【神ヘアオイル】エルジューダMOの正しい使い方", views: "89万", url: YT("エルジューダ MO 使い方 ヘアオイル ミルボン") },
  },
  {
    id: 7, cat: "ヘアケア", sub: "ヘアオイル", name: "N.ポリッシュオイル", brand: "ナプラ",
    price: 3080, rating: 4.6, rev: 9800, free: true,
    desc: "スタイリング兼用マルチオイル。重さゼロでツヤだけ与える。熱保護なし。",
    tags: ["ヘアオイル", "熱保護なし", "ツヤ感", "細め・柔らか"],
    image: U("1522338242992-e1a54906a8da"),
    note: "TikTokで爆発的に話題になったスタイリングオイルの代名詞。",
    video: { title: "N.ポリッシュ｜TikTokで話題の使い方3選", views: "124万", url: YT("N.ポリッシュオイル 使い方 スタイリング ナプラ") },
  },
  {
    id: 8, cat: "ヘアケア", sub: "シャンプー", name: "ボタニカルシャンプー モイスト", brand: "BOTANIST",
    price: 1650, rating: 4.3, rev: 28600, free: true,
    desc: "植物由来成分90%以上。泡立ちよく、しっとりまとまる髪へ。",
    tags: ["乾燥", "しっとり", "カラー毛", "ダメージ毛"],
    image: U("1585297418628-a4cbb53f2d70"),
    note: "市販シャンプーで最多の口コミ数を誇るヒット商品。",
    video: { title: "ボタニスト本当にいいの？美容師が本音レビュー", views: "45万", url: YT("BOTANIST ボタニスト シャンプー 美容師 レビュー") },
  },
  {
    id: 9, cat: "ヘアケア", sub: "トリートメント", name: "ユイル スブリム ビューテ", brand: "Kérastase",
    price: 6600, rating: 4.9, rev: 3400, free: false,
    desc: "サロン専売級補修力。カラー褪色を防ぎながら内部から集中補修。",
    tags: ["熱保護あり", "ダメージ補修", "剛毛・硬め", "カラー毛"],
    image: U("1519461797-7b8dc4b44f0c"),
    note: "フランス発サロンブランドの代表作。一度使うと戻れない質感。",
    video: { title: "【美容師本音】ケラスターゼは本当に効く？", views: "45万", url: YT("Kérastase ケラスターゼ ユイル トリートメント 効果") },
  },
  {
    id: 10, cat: "ヘアケア", sub: "ヘアマスク", name: "PRO HAIR MASK ディープモイスト", brand: "LUX",
    price: 1408, rating: 4.2, rev: 15200, free: false,
    desc: "ボンドケア技術で毛髪内部の結合を補修。週2回のサロン級集中ケア。",
    tags: ["ダメージ補修", "乾燥", "カラー毛", "しっとり"],
    image: U("1585297418628-a4cbb53f2d70"),
    note: "市販ヘアマスクの中で補修力が特に高い評価を受けている一品。",
    video: { title: "市販トリートメント最強決定戦2024", views: "178万", url: YT("LUX ヘアマスク トリートメント ダメージ補修 比較") },
  },
  // メイク
  {
    id: 11, cat: "メイク", sub: "ファンデーション", name: "ライトリフレクティング ファンデ", brand: "NARS",
    price: 7150, rating: 4.6, rev: 6700, free: true,
    desc: "光を味方に自然なカバー力。密着力が高くテカリにくい崩れにくさ。",
    tags: ["混合肌", "毛穴", "カバー", "崩れにくい"],
    image: U("1512290923902-8a9f81dc236c"),
    note: "ハイエンドファンデの中でも特に肌馴染みが絶賛される名品。",
    video: { title: "NARS新作ファンデ｜6時間後の仕上がりを見て", views: "98万", url: YT("NARS ファンデーション 使い方 崩れにくい レビュー") },
  },
  {
    id: 12, cat: "メイク", sub: "リップ", name: "Juicy Lasting Tint", brand: "rom&nd",
    price: 1430, rating: 4.7, rev: 22300, free: true,
    desc: "韓国コスメ発の超優秀ティント。落ちにくく発色が鮮やか。",
    tags: ["プチプラ", "発色", "落ちにくい", "韓国コスメ"],
    image: U("1586495777744-4e6232bf2176"),
    note: "日本でも入手しやすい韓国コスメリップの定番中の定番。",
    video: { title: "rom&nd全色レビュー｜どれが一番映える？", views: "203万", url: YT("rom&nd ジューシーラスティングティント 全色 レビュー") },
  },
  {
    id: 13, cat: "メイク", sub: "チーク", name: "クリームチーク", brand: "CANMAKE",
    price: 748, rating: 4.5, rev: 41200, free: true,
    desc: "ジューシーな血色感。指でぽんぽんなじませるだけ。超プチプラ。",
    tags: ["プチプラ", "血色感", "ナチュラル", "初心者向け"],
    image: U("1487412168867-2b56477c4a72"),
    note: "ドラッグストアで買えるのに本格的な血色感を演出できる。",
    video: { title: "キャンメイクチーク神すぎ問題【全色比較】", views: "156万", url: YT("CANMAKE キャンメイク クリームチーク 全色 使い方") },
  },
  {
    id: 14, cat: "メイク", sub: "アイシャドウ", name: "Multi Eye Color Palette", brand: "3CE",
    price: 3520, rating: 4.4, rev: 9100, free: false,
    desc: "韓国ブランドの洗練パレット。マットからグリッターまで12色展開。",
    tags: ["韓国コスメ", "バリエーション", "デイリー", "パーティー"],
    image: U("1487412168867-2b56477c4a72"),
    note: "韓国アイドルメイクを自宅で再現できるとSNSで話題沸騰。",
    video: { title: "3CEパレット全種比較｜初心者でも使えるのは？", views: "67万", url: YT("3CE アイシャドウパレット 使い方 韓国コスメ") },
  },
  {
    id: 15, cat: "メイク", sub: "コンシーラー", name: "カバーフィットコンシーラー", brand: "Cezanne",
    price: 638, rating: 4.3, rev: 18800, free: false,
    desc: "クマ・毛穴・ニキビ跡をカバー。ヨレにくくプチプラで優秀。",
    tags: ["プチプラ", "クマ", "ニキビ跡", "初心者向け"],
    image: U("1512290923902-8a9f81dc236c"),
    note: "この価格帯では断トツのカバー力を誇るドラッグストアコスメ。",
    video: { title: "コンシーラーの正しい使い方｜プロが解説", views: "89万", url: YT("Cezanne セザンヌ コンシーラー クマ 使い方") },
  },
  // ボディ
  {
    id: 16, cat: "ボディ", sub: "ボディクリーム", name: "INTACT ボディクリーム", brand: "Nivea",
    price: 1078, rating: 4.4, rev: 19300, free: true,
    desc: "セラミド配合で乾燥肌をしっかり保湿。伸びがよく浸透力高い。",
    tags: ["乾燥", "保湿", "プチプラ", "敏感肌OK"],
    image: U("1571019613454-1cb2f99b2d8b"),
    note: "年齢・性別問わず使えるボディケアの永遠の定番。",
    video: { title: "ニベアの底力｜コスパ最強ボディケア", views: "78万", url: YT("Nivea ニベア ボディクリーム 保湿 使い方") },
  },
  {
    id: 17, cat: "ボディ", sub: "スクラブ", name: "ソルト & フラワー スクラブ", brand: "SABON",
    price: 4290, rating: 4.6, rev: 5600, free: true,
    desc: "死海の塩とフラワーオイルで全身をつるつるに。香りも最高。",
    tags: ["角質ケア", "保湿", "香り", "ギフト"],
    image: U("1574700624218-e3dbb4490e74"),
    note: "ギフトとしても大人気。使用後の肌がまるで赤ちゃんのような質感に。",
    video: { title: "SABON神スクラブ｜使い方と効果を徹底解説", views: "34万", url: YT("SABON サボン スクラブ 使い方 効果") },
  },
  {
    id: 18, cat: "ボディ", sub: "バーム", name: "エターナルゴールド バーム", brand: "Aesop",
    price: 8800, rating: 4.8, rev: 2800, free: false,
    desc: "タスマニアペッパーリーフ配合。肌をなめらかに整えるラグジュアリーバーム。",
    tags: ["高保湿", "香り", "ラグジュアリー", "ギフト"],
    image: U("1585747860715-2ba37e788b70"),
    note: "Aesopの哲学が凝縮された、贈りたい一品。使うたびに特別な気分に。",
    video: { title: "Aesopで変わった私の肌【高級ボディケア】", views: "25万", url: YT("Aesop イソップ ボディ バーム レビュー") },
  },
  // UVケア
  {
    id: 19, cat: "UVケア", sub: "日焼け止め", name: "クロノビューティ SPF50+", brand: "ALLIE",
    price: 1980, rating: 4.7, rev: 31400, free: true,
    desc: "汗・水・皮脂に強い。ウォータープルーフで一日中UV防御。",
    tags: ["SPF50+", "ウォータープルーフ", "混合肌"],
    image: U("1618354691438-25bc04584c23"),
    note: "夏のアウトドアからデイリー使いまでカバーする優等生UV。",
    video: { title: "日焼け止め最強ランキング2024【皮膚科医監修】", views: "312万", url: YT("ALLIE アリー 日焼け止め SPF50 レビュー 比較") },
  },
  {
    id: 20, cat: "UVケア", sub: "日焼け止め", name: "トーンアップ UV ラベンダー", brand: "SKIN AQUA",
    price: 990, rating: 4.5, rev: 28700, free: true,
    desc: "ラベンダーカラーでくすみを補正。美容液成分で肌を守りながら整える。",
    tags: ["くすみ補正", "保湿", "プチプラ", "下地兼用"],
    image: U("1618354691438-25bc04584c23"),
    note: "下地いらずで透明感が出る、忙しい朝の強い味方。",
    video: { title: "スキンアクアトーンアップ全色比較", views: "145万", url: YT("スキンアクア トーンアップUV 全色 比較 使い方") },
  },
  {
    id: 21, cat: "UVケア", sub: "UVファンデ", name: "プロテクティブ UVファンデ", brand: "IPSA",
    price: 5500, rating: 4.6, rev: 4100, free: false,
    desc: "UV防止＋ファンデ機能を兼備。ハイエンドな仕上がりで崩れにくい。",
    tags: ["SPF50+", "下地兼用", "高保湿", "エイジングケア"],
    image: U("1544215175-e0ea59b0ff43"),
    note: "一本でスキンケア・UV・ファンデが完結する時短の究極形。",
    video: { title: "イプサ日焼け止め｜一日中崩れない理由", views: "28万", url: YT("IPSA イプサ UV ファンデーション 崩れない") },
  },
  // フレグランス
  {
    id: 22, cat: "フレグランス", sub: "香水", name: "ピオニー＆ブラッシュスエード", brand: "Jo Malone",
    price: 22000, rating: 4.9, rev: 4500, free: true,
    desc: "甘く上品なフローラル。ピオニーとスエードのエレガントな香り。",
    tags: ["フローラル", "甘め", "デート", "ギフト"],
    image: U("1523293182086-7651a899d37f"),
    note: "Jo Maloneの中でも日本で特に人気の高いシグネチャーフレグランス。",
    video: { title: "ジョーマローン全香水ランキング｜プロが正直に", views: "89万", url: YT("Jo Malone ジョーマローン ピオニー レビュー 香り") },
  },
  {
    id: 23, cat: "フレグランス", sub: "ボディミスト", name: "ローズジャスミン ボディミスト", brand: "The Body Shop",
    price: 2970, rating: 4.3, rev: 8900, free: true,
    desc: "フレッシュなローズとジャスミン。日常使いしやすい軽い香り。",
    tags: ["フローラル", "軽め", "プチプラ", "デイリー"],
    image: U("1543362906-acfc16c2551b"),
    note: "プチプラで毎日使えるフレグランスの入門として最適。",
    video: { title: "プチプラ香水の最適解｜ボディミスト比較", views: "67万", url: YT("The Body Shop ボディミスト 香水 プチプラ おすすめ") },
  },
  {
    id: 24, cat: "フレグランス", sub: "香水", name: "N°5 オードゥパルファム", brand: "CHANEL",
    price: 38500, rating: 4.8, rev: 2100, free: false,
    desc: "100年以上愛され続ける伝説の香り。アルデヒドフローラルの代名詞。",
    tags: ["フローラル", "クラシック", "大人", "ラグジュアリー"],
    image: U("1523293182086-7651a899d37f"),
    note: "世界で最も有名な香水。一度纏えばその理由がわかる普遍的な美しさ。",
    video: { title: "シャネル5番の魅力｜なぜ100年愛されるのか", views: "145万", url: YT("CHANEL No5 シャネル 5番 香水 歴史 レビュー") },
  },
  // ネイル
  {
    id: 25, cat: "ネイル", sub: "ネイルカラー", name: "ジェルカラー コレクション", brand: "OPI",
    price: 1980, rating: 4.5, rev: 12300, free: true,
    desc: "300色以上の豊富なカラー。サロン級の発色と持ちを自宅で。",
    tags: ["発色", "長持ち", "サロン仕上げ", "バリエーション"],
    image: U("1604654894610-df63bc536371"),
    note: "世界中のネイルアーティストが愛用するプロ仕様ブランド。",
    video: { title: "OPIネイル神カラー2024｜流行りはこれ", views: "78万", url: YT("OPI ネイルカラー 2024 おすすめ セルフネイル") },
  },
  {
    id: 26, cat: "ネイル", sub: "ネイルケア", name: "ネイルオイル ペン", brand: "uka",
    price: 2750, rating: 4.7, rev: 6800, free: true,
    desc: "ロールオンタイプで持ち運びしやすい。爪・甘皮を集中保湿。",
    tags: ["ネイルケア", "保湿", "持ち運び", "甘皮ケア"],
    image: U("1604654894610-df63bc536371"),
    note: "ネイリストも絶賛する美しい爪を育てるためのセルフケアの基本。",
    video: { title: "爪の保湿ケア入門｜ネイルオイルの使い方", views: "34万", url: YT("uka ウカ ネイルオイル 使い方 甘皮ケア") },
  },
  {
    id: 27, cat: "ネイル", sub: "ジェルキット", name: "ジェルネイルキット スターター", brand: "Gelish",
    price: 12800, rating: 4.6, rev: 3200, free: false,
    desc: "LEDライト付きの本格ジェルネイルキット。セルフで3〜4週間持続。",
    tags: ["ジェルネイル", "セルフ", "長持ち", "初心者向け"],
    image: U("1604654894610-df63bc536371"),
    note: "サロンに通うコストを大幅削減。初めてのセルフジェルに最適なスターターキット。",
    video: { title: "セルフジェルネイル完全攻略｜初心者でもできる", views: "201万", url: YT("ジェルネイル セルフ 初心者 やり方 Gelish") },
  },
  // サプリ
  {
    id: 28, cat: "サプリ", sub: "ビタミン", name: "ビタミンC ハイポテンシー", brand: "DHC",
    price: 980, rating: 4.5, rev: 38200, free: true,
    desc: "1粒1000mgの高濃度ビタミンC。美白・コラーゲン生成をサポート。",
    tags: ["美白", "コラーゲン", "プチプラ", "毎日"],
    image: U("1584308666744-24d5c474f2ae"),
    note: "美容の基本中の基本。DHCが誇るロングセラーのビタミンCサプリ。",
    video: { title: "ビタミンCサプリ選び方【美容専門家が解説】", views: "123万", url: YT("DHC ビタミンC サプリ 美白 効果 摂り方") },
  },
  {
    id: 29, cat: "サプリ", sub: "コラーゲン", name: "コラーゲン ドリンク プレミアム", brand: "明治",
    price: 3240, rating: 4.3, rev: 15600, free: true,
    desc: "低分子コラーゲン10000mg配合。30日分の飲みやすいゼリータイプ。",
    tags: ["コラーゲン", "ハリ", "エイジングケア", "飲みやすい"],
    image: U("1559657218-6ddf8c0d0edf"),
    note: "続けやすい美味しさと手軽さが支持される定番インナービューティー。",
    video: { title: "コラーゲンサプリ本当に効く？1ヶ月実験", views: "89万", url: YT("コラーゲン ドリンク 効果 1ヶ月 体験談") },
  },
  {
    id: 30, cat: "サプリ", sub: "抗酸化", name: "グレープシードエキス複合体", brand: "Ester-C",
    price: 4200, rating: 4.6, rev: 5400, free: false,
    desc: "抗酸化・紫外線ダメージ対策のトータルサポート。美容感度の高い人に。",
    tags: ["抗酸化", "美白", "紫外線対策", "エイジングケア"],
    image: U("1584308666744-24d5c474f2ae"),
    note: "皮膚科医・美容家が口を揃えておすすめする高機能アンチエイジングサプリ。",
    video: { title: "美容皮膚科が飲んでるサプリTop5", views: "445万", url: YT("グレープシード 抗酸化 サプリ 美容 効果") },
  },
];

export const ALL_TAGS = [...new Set(PRODUCTS.flatMap((p) => p.tags))];

export const CONCERNS = [
  "乾燥", "毛穴", "くすみ", "ニキビ", "赤み",
  "ダメージ毛", "うねり", "エイジング", "皮脂過多", "UV対策",
];
